# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

defaults: &startContainer
    working_directory: ~/react-components
    docker:
        - image: circleci/node:7.10

defaults: &npmInstall
    name: Installing all dependencies
    command: npm install

version: 2
jobs:
    test-job:
        <<: *startContainer
        steps:
            - checkout
            - restore_cache:
                keys:
                    - app-dependencies-v1-{{ checksum "package.json" }}
            - run:
                <<: *npmInstall
            - save_cache:
                key: app-dependencies-v1-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Running the tests
                command: npm run test
workflows:
    version: 2
    build-deploy:
        jobs:
            - test-job